### ISSUE TITLE
It seems that the Equation 2 of the manuscript is incomplete

### ISSUE THREAD

**Issue by hongyaohongyao** [rezazzr/breadcrumbs#2]
Or I misunderstood something.

**Comment by rezazzr** [comment]
Hello,
To better understand Equation 2 in the manuscript, it's important to consider the context provided in the paragraphs preceding and following its appearance. The equation is not self-contained, and its meaning becomes clearer when read in conjunction with the surrounding text. Feel free to review the nearby content, and if you have any questions or need further clarification, I'd be happy to assist.
![Screenshot from 2024-01-11 12-25-56](https://github.com/rezazzr/breadcrumbs/assets/29124068/60339a5d-f7e4-479c-af04-78cb7f5d7c79)
